package net.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("net.duck8823.GenerateNamesProcessor")
public class HogeCreateFieldsNames {

	/**
	 * abstractHogeのフィールド名
	 */
	public static final String ABSTRACT_HOGE = "abstractHoge";

	/**
	 * hogeのフィールド名
	 */
	public static final String HOGE = "hoge"

	/**
	 * abstractHogeのフィールド名を取得します.
	 * @return abstractHogeのフィールド名
	 */
	public final String abstractHoge() {
		return "abstractHoge";
	}

	/**
	 * hogeのフィールド名を取得します.
	 * @return hogeのフィールド名
	 */
	public final String hoge() {
		return "hoge";
	}
}