package com.github.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("GenerateNamesProcessor")
public class HogeNames {
	/**
	 * abstractHogeのフィールド名を取得します.
	 * @return abstractHogeのフィールド名
	 */
	public final String abstractHoge() {
		return "abstractHoge";
	}

	/**
	 * hogeのフィールド名を取得します.
	 * @return hogeのフィールド名
	 */
	public final String hoge() {
		return "hoge";
	}
}
