package com.github.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("GenerateNamesProcessor")
public class HogeCreateFieldsNames {

	/**
	 * abstractHogeのフィールド名
	 */
	public static final String ABSTRACT_HOGE = "abstractHoge";

	/**
	 * hogeのフィールド名
	 */
	public static final String HOGE = "hoge"

}
