package com.github.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("GenerateNamesProcessor")
public class HogeCreateMethodsNames {

	/**
	 * toString()のメソッド名
	 */
	public static final String TO_STRING = "toString"

	/**
	 * hogeのフィールド名
	 */
	public static final String HOGE = "hoge"

	/**
	 * toString()のメソッド名を取得します.
	 * @return hogeのメソッド名
	 */
	public final String toString() {
		return "toString";
	}

	/**
	 * hogeのフィールド名を取得します.
	 * @return hogeのフィールド名
	 */
	public final String hoge() {
		return "hoge";
	}
}
