package net.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("net.duck8823.GenerateNamesProcessor")
public class HogeRelatedNames {
	/**
	 * hogeEmbeddableのフィールド名
	 */
	public static final String HOGE_EMBEDDABLE = "hogeEmbeddable";

	/**
	 * hogeOneToManyのフィールド名
	 */
	public static final String HOGE_ONE_TO_MANY = "hogeOneToMany";

	/**
	 * hogeManyToManyのフィールド名
	 */
	public static final String HOGE_MANY_TO_MANY = "hogeManyToMany";

	/**
	 * oneToOneElemのフィールド名
	 */
	public static final String ONE_TO_ONE_ELEM = "oneToOneElem";

	/**
	 * embeddableElemのフィールド名
	 */
	public static final String EMBEDDABLE_ELEM = "embeddableElem";

	/**
	 * hogeManyToOneのフィールド名
	 */
	public static final String HOGE_MANY_TO_ONE = "hogeManyToOne";

	/**
	 * oneToManyElemのフィールド名
	 */
	public static final String ONE_TO_MANY_ELEM = "oneToManyElem";

	/**
	 * abstractHogeのフィールド名
	 */
	public static final String ABSTRACT_HOGE = "abstractHoge";

	/**
	 * hogeOneToOneのフィールド名
	 */
	public static final String HOGE_ONE_TO_ONE = "hogeOneToOne";

	/**
	 * manyToOneElemのフィールド名
	 */
	public static final String MANY_TO_ONE_ELEM = "manyToOneElem";

	/**
	 * hogeのフィールド名
	 */
	public static final String HOGE = "hoge";

	/**
	 * manyToManyElemのフィールド名
	 */
	public static final String MANY_TO_MANY_ELEM = "manyToManyElem";
}