package com.github.duck8823;

import java.lang.String;
import javax.annotation.Generated;

/**
 * Generated by generate-names.
 * @see https://github.com/duck8823/generate-names
 */
@Generated("GenerateNamesProcessor")
public class HogeRelatedNames {
	/**
	 * hogeEmbeddableのフィールド名
	 */
	public static final String HOGE_EMBEDDABLE = "hogeEmbeddable";

	/**
	 * hogeOneToManyのフィールド名
	 */
	public static final String HOGE_ONE_TO_MANY = "hogeOneToMany";

	/**
	 * hogeManyToManyのフィールド名
	 */
	public static final String HOGE_MANY_TO_MANY = "hogeManyToMany";

	/**
	 * hogeManyToOne.manyToOneElemのフィールド名
	 */
	public static final String HOGE_MANY_TO_ONE_MANY_TO_ONE_ELEM = "hogeManyToOne.manyToOneElem";

	/**
	 * hogeManyToOneのフィールド名
	 */
	public static final String HOGE_MANY_TO_ONE = "hogeManyToOne";

	/**
	 * abstractHogeのフィールド名
	 */
	public static final String ABSTRACT_HOGE = "abstractHoge";

	/**
	 * hogeOneToOneのフィールド名
	 */
	public static final String HOGE_ONE_TO_ONE = "hogeOneToOne";

	/**
	 * hogeOneToOne.oneToOneElemのフィールド名
	 */
	public static final String HOGE_ONE_TO_ONE_ONE_TO_ONE_ELEM = "hogeOneToOne.oneToOneElem";

	/**
	 * hogeのフィールド名
	 */
	public static final String HOGE = "hoge";

	/**
	 * hogeOneToMany.oneToManyElemのフィールド名
	 */
	public static final String HOGE_ONE_TO_MANY_ONE_TO_MANY_ELEM = "hogeOneToMany.oneToManyElem";

	/**
	 * hogeManyToMany.manyToManyElemのフィールド名
	 */
	public static final String HOGE_MANY_TO_MANY_MANY_TO_MANY_ELEM = "hogeManyToMany.manyToManyElem";

	/**
	 * hogeEmbeddable.embeddableElemのフィールド名
	 */
	public static final String HOGE_EMBEDDABLE_EMBEDDABLE_ELEM = "hogeEmbeddable.embeddableElem";
}
